 <footer>
       
    </footer><!--/#footer-->

    <script src="<?=$this->basePath() . '/public/js/adminjs/jquery.js'?> "></script>
    <script src="<?=$this->basePath() . '/public/js/adminjs/bootstrap.min.js'?>"></script>
    <script src="<?=$this->basePath() . '/public/js/adminjs/main.js'?>"></script>
    
    
    <link href="<?=$this->basePath() . '/public/css/admincss/font-awesome.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/admincss/bootstrap.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/admincss/animate.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/admincss/main.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/admincss/responsive.css'?>" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
</body>
</html>