<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | Hireapplicants</title>
	
	<!-- core CSS -->
    
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    
</head><!--/head-->
<body>

    <header id="header">
        <!--<div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-xs-4">
                        <div class="top-number"><p><i class="fa fa-phone-square"></i>  +919810669912</p></div>
                    </div>
                    
                </div>
            </div>
        </div> -->

        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button> -->
                    <a class="navbar-brand" href="<?=$GLOBALS['SITE_ADMIN_URL']?>"><img src=" <?=$this->basePath() . '/public/img/adminimages/logo.png'?> " alt="logo"></a>
                </div>
				
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hi User <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Profile</a></li>
                                <li><a href="<?=$GLOBALS['SITE_ADMIN_URL']?>common/logout">LogOut</a></li>
                               
                            </ul>
                        </li>
                      
                                             
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
		
		
		
    </header><!--/header-->
    
    <script>
        var serverUrl ='<?php echo $GLOBALS['SITE_ADMIN_URL']; ?>';
    </script>
    
    