<!--<ul>
    <li> <a href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/countrylist"> country list</a></li>
    <li> <a href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/statelist"> State list</a></li>
    <li> <a href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/emailsetuplist"> Email Setup</a></li>
</ul>-->

<section id="error" class="container">
	<div class="col-xs-12 col-sm-2 col-md-12" >
	
	<ul class="portfolio-filter text-center">
                <li><a class="btn btn-default" href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/countrylist" >Country</a></li>
                <li><a class="btn btn-default" href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/statelist">State</a></li>
                <li><a class="btn btn-default" href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/emailsetuplist">Email Templates</a></li>
                <li><a class="btn btn-default" href="<?=$GLOBALS['SITE_ADMIN_URL']?>dashboard/newcompanylist">New Company</a></li>
            </ul>
	
	
	</div>
		<div class="col-xs-12 col-sm-2 col-md-12" >
	
	<ul class="portfolio-filter text-center">
                <li><a class="btn btn-default" href="#" >Users</a></li>
                <li><a class="btn btn-default" href="#">Companies</a></li>
                <li><a class="btn btn-default" href="#">Coupon</a></li>
                <li><a class="btn btn-default" href="#">Pricing</a></li>
            </ul>
	
	
	</div>
			<div class="col-xs-12 col-sm-2 col-md-12" >
	
	<ul class="portfolio-filter text-center">
                <li><a class="btn btn-default" href="#" >Company Report</a></li>
                <li><a class="btn btn-default" href="#">SMS Report</a></li>
                <li><a class="btn btn-default" href="#">Applicant Status</a></li>
                <li><a class="btn btn-default" href="#">Billing info</a></li>
            </ul>
	
	
	</div>
		<ul class="portfolio-filter text-center">
                <li><a class="btn btn-default" href="#" >Phone Number</a></li>
                <li><a class="btn btn-default" href="#">Send Message</a></li>
                <li><a class="btn btn-default" href="#">View Message</a></li>
               
            </ul>
	
	
	</div>
	
       
    </section><!--/#error-->