<body class="body-wrapper  changeHeader ">
  <div class="main-wrapper">

    <!-- HEADER -->
    <header>
      <nav class="navbar navbar-default navbar-main navbar-fixed-top" role="navigation">
		<div class="top_header">
			<div class="container">
				<div class="row">
					<div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
						<i class="fa fa-phone-square" aria-hidden="true"></i> &nbsp;8130450522 &nbsp;&nbsp;&nbsp;
						<i class="fa fa-envelope" aria-hidden="true"></i>&nbsp; raviducat@gmail.com
					</div>
					<div class="col-sm-6 col-md-6 col-lg-6 col-xs-12 pull-right">
						<a style="color:#fff;" class="pull-right" href="" data-toggle="modal" data-target="#signup">Signup</a>
						<a style="color:#fff;margin-right:10px;" class="pull-right" href="" data-toggle="modal" data-target="#login">Login</a>
					</div>					
				</div>
			</div>
		</div>
        <div class="container">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
				<a class="navbar-brand" href="index.html"></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
<li class="dropdown singleDrop active">
<a href="index.html">Home</a>
</li>
<li class="dropdown singleDrop">
	<a href="pakagelist.html">tour packages</a>
</li>
<li class="dropdown singleDrop">
	<a href="aboutus.html">about us</a>
</li>
<li class="dropdown singleDrop">
	<a href="contactus.html">contact us</a>
</li>
<li class="dropdown singleDrop">
	<a href="gallery.html">gallery</a>
</li>             
              <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="searchIcon"><i class="fa fa-search" aria-hidden="true"></i></span></a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li>
                    <span class="input-group">
                      <input type="text" class="form-control" placeholder="Search..." aria-describedby="basic-addon2">
                      <span class="input-group-addon" id="basic-addon2">Search</span>
                    </span>
                  </li>
                </ul>
              </li>
            </ul>
          </div>

        </div>
      </nav>
    </header>


    <!-- BANNER -->
    <section class="bannercontainer">
      <div class="fullscreenbanner-container">
        <div class="fullscreenbanner">
          <ul>
            <li data-transition="parallaxvertical" data-slotamount="5" data-masterspeed="700" data-title="Slide 1">
              <img src="img/home/slider/slider-01.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
              <div class="slider-caption container">
                <div class="tp-caption rs-caption-1 sft start"
                  data-hoffset="0"
                  data-y="270"
                  data-speed="800"
                  data-start="1000"
                  data-easing="Back.easeInOut"
                  data-endspeed="300">
                  Discover The Most Amazing
                  <span>Travel Template</span>
                </div>
                <div class="tp-caption rs-caption-2 sft"
                  data-hoffset="0"
                  data-y="400"
                  data-speed="1000"
                  data-start="1500"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex consequat.
                </div>
                <div class="tp-caption rs-caption-3 sft"
                  data-hoffset="0"
                  data-y="485"
                  data-speed="800"
                  data-start="2000"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  <span class="page-scroll"><a target="_blank" href="http://goo.gl/lXpsqr" class="btn buttonCustomPrimary">Buy Now</a></span>
                </div>
              </div>
            </li>
            <li data-transition="parallaxvertical" data-slotamount="5" data-masterspeed="1000" data-title="Slide 2">
              <img src="img/home/slider/slider-02.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
              <div class="slider-caption container">
                <div class="tp-caption rs-caption-1 sft start text-center"
                  data-hoffset="0"
                  data-x="center"
                  data-y="270"
                  data-speed="800"
                  data-start="1000"
                  data-easing="Back.easeInOut"
                  data-endspeed="300">
                  Crossing The Limits
                  <span>Star Travel</span>
                </div>
                <div class="tp-caption rs-caption-2 sft text-center"
                  data-hoffset="0"
                  data-x="center"
                  data-y="400"
                  data-speed="1000"
                  data-start="1500"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  Maecenas nec sodales justo. Vivamus auctor pulvinar mattis. Ut at elementum nunc. Quisque condimentum ligula ante, non luctus enim pulvinar sed. Fusce quis congue odio.
                </div>
                <div class="tp-caption rs-caption-3 sft text-center"
                  data-hoffset="0"
                  data-x="center"
                  data-y="485"
                  data-speed="800"
                  data-start="2000"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  <span class="page-scroll"><a target="_blank" href="http://goo.gl/lXpsqr" class="btn buttonCustomPrimary">Read More</a></span>
                </div>
              </div>
            </li>
            <li data-transition="parallaxvertical" data-slotamount="5" data-masterspeed="700" data-title="Slide 1">
              <img src="img/home/slider/slider-03.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
              <div class="slider-caption container">
                <div class="tp-caption rs-caption-1 sft start"
                  data-hoffset="0"
                  data-y="270"
                  data-speed="800"
                  data-start="1000"
                  data-easing="Back.easeInOut"
                  data-endspeed="300">
                  Enjoy Ultimate Freedom
                  <span>Bootstrap Theme</span>
                </div>
                <div class="tp-caption rs-caption-2 sft"
                  data-hoffset="0"
                  data-y="400"
                  data-speed="1000"
                  data-start="1500"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  Aenean congue nisi elit, vitae viverra leo luctus et. Donec interdum erat id mi scelerisque, vitae ullamcorper lorem gravida. Nunc sed maximus ante. Nulla dictum turpis vitae vehicula auctor.
                </div>
                <div class="tp-caption rs-caption-3 sft"
                  data-hoffset="0"
                  data-y="485"
                  data-speed="800"
                  data-start="2000"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  <span class="page-scroll"><a target="_blank" href="http://goo.gl/lXpsqr" class="btn buttonCustomPrimary">Buy Now</a></span>
                </div>
              </div>
            </li>
            <li data-transition="parallaxvertical" data-slotamount="5" data-masterspeed="1000" data-title="Slide 2">
              <img src="img/home/slider/slider-04.jpg" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
              <div class="slider-caption container">
                <div class="tp-caption rs-caption-1 sft start text-center"
                  data-hoffset="0"
                  data-x="center"
                  data-y="270"
                  data-speed="800"
                  data-start="1000"
                  data-easing="Back.easeInOut"
                  data-endspeed="300">
                  Go Where You Wanna Go
                  <span>24/7 Quick Support</span>
                </div>
                <div class="tp-caption rs-caption-2 sft text-center"
                  data-hoffset="0"
                  data-x="center"
                  data-y="400"
                  data-speed="1000"
                  data-start="1500"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  Maecenas et leo nec nunc rutrum tempor. Mauris pharetra porttitor odio eget convallis. Praesent facilisis mattis pretium. Aliquam sagittis efficitur risus, interdum euismod urna. Pellentesque vel augue augue.
                </div>
                <div class="tp-caption rs-caption-3 sft text-center"
                  data-hoffset="0"
                  data-x="center"
                  data-y="485"
                  data-speed="800"
                  data-start="2000"
                  data-easing="Power4.easeOut"
                  data-endspeed="300"
                  data-endeasing="Power1.easeIn"
                  data-captionhidden="off">
                  <span class="page-scroll"><a target="_blank" href="http://goo.gl/lXpsqr" class="btn buttonCustomPrimary">View Delails</a></span>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </section>

    <!-- SEARCH TOUR -->
    <section class="darkSection">
      <div class="container">
        <div class="row gridResize">
          <div class="col-sm-3 col-xs-12">
            <div class="sectionTitleDouble">
              <p>Search</p>
              <h2>your <span>tours</span></h2>
            </div>
          </div>
          <div class="col-sm-7 col-xs-12">
            <div class="row">
              <div class="col-sm-3 col-xs-12">
                <div class="searchTour">
                  <select name="guiest_id2" id="guiest_id2" class="select-drop">
                    <option value="0">Destinations</option>
                    <option value="1">USA</option>
                    <option value="2">UK</option>
                    <option value="3">Canada</option>
                  </select>
                </div>
              </div>
              <div class="col-sm-3 col-xs-12">
                <div class="input-group date ed-datepicker" data-provide="datepicker">
                  <input type="text" class="form-control" placeholder="MM/DD/YYYY">
                  <div class="input-group-addon">
                      <span class="fa fa-calendar"></span>
                  </div>
                </div>
              </div>
              <div class="col-sm-3 col-xs-12">
                <div class="input-group date ed-datepicker" data-provide="datepicker">
                  <input type="text" class="form-control" placeholder="MM/DD/YYYY">
                  <div class="input-group-addon">
                      <span class="fa fa-calendar"></span>
                  </div>
                </div>
              </div>
              <div class="col-sm-3 col-xs-12">
                <div class="searchTour">
                  <select name="guiest_id3" id="guiest_id3" class="select-drop">
                    <option value="0">$1000 - $2000</option>
                    <option value="1">$1400 - $2000</option>
                    <option value="2">$1600 - $2000</option>
                    <option value="3">$1800 - $2000</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-2 col-xs-12">
            <a href="#" class="btn btn-block buttonCustomPrimary">Search</a>
          </div>
        </div>
      </div>
    </section>

    <!-- TOP DEALS -->
    <section class="mainContentSection packagesSection">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="sectionTitle">
              <h2><span class="lightBg">Our Top Deals</span></h2>
              <p>Quisque lacus augue, blandit non est a, dictum malesuada odio.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 col-xs-12">
            <div class="thumbnail deals">
              <img src="img/home/deal/deal-01.jpg" alt="deal-image">
              <a href="single-package-right-sidebar.html" class="pageLink"></a>
              <div class="discountInfo">
                <div class="discountOffer">
                  <h4>
                    50% <span>OFF</span>
                  </h4>
                </div>
                <ul class="list-inline rating homePage">
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                </ul>
                <ul class="list-inline duration">
                  <li>7 days</li>
                  <li>15 hrs</li>
                  <li>15 min</li>
                </ul>
              </div>
              <div class="caption">
                <h4><a href="single-package-right-sidebar.html" class="captionTitle">Suspendisse Blandit</a></h4>
                <p>Integer purus ex, dictum nec elementum eu, tristique vel lectus. Donec rutrum lectus et pharetra egestas.</p>
                <div class="detailsInfo">
                  <h5>
                    <span>Start From</span>
                    $299
                  </h5>
                  <ul class="list-inline detailsBtn">
                    <li><a href="single-package-right-sidebar.html" class="btn buttonTransparent buttonCustomPrimary">Details</a></li>
                    <li><a href='booking-1.html' class="btn buttonTransparent buttonCustomPrimary">Book now</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="thumbnail deals">
              <img src="img/home/deal/deal-02.jpg" alt="deal-image">
              <a href="single-package-fullwidth.html" class="pageLink"></a>
              <div class="discountInfo">
                <div class="discountOffer">
                  <h4>
                    Free <span>Gift</span>
                  </h4>
                </div>
                <ul class="list-inline rating homePage">
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                </ul>
                <ul class="list-inline duration">
                  <li>12 days</li>
                  <li>3 hrs</li>
                  <li>12 min</li>
                </ul>
              </div>
              <div class="caption">
                <h4><a href="single-package-fullwidth.html" class="captionTitle">Suspendisse Eros Erat</a></h4>
                <p>Proin convallis magna vel libero accumsan sollicitudin. Quisque dapibus vitae turpis eu magna sagittis.</p>
                <div class="detailsInfo">
                  <h5>
                    <span>Start From</span>
                    $499
                  </h5>
                  <ul class="list-inline detailsBtn">
                    <li><a href="single-package-right-sidebar.html" class="btn buttonTransparent buttonCustomPrimary">Details</a></li>
                    <li><a data-toggle="modal" data-target="#inquiryModal" href="#" class="btn buttonTransparent buttonCustomPrimary">Inquiry</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-xs-12">
            <div class="thumbnail deals">
              <img src="img/home/deal/deal-03.jpg" alt="deal-image">
              <a href="single-package-right-sidebar.html" class="pageLink"></a>
              <div class="discountInfo">
                <div class="discountOffer">
                  <h4>
                    25% <span>OFF</span>
                  </h4>
                </div>
                <ul class="list-inline rating homePage">
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                  <li><i class="fa fa-star" aria-hidden="true"></i></li>
                </ul>
                <ul class="list-inline duration">
                  <li>17 days</li>
                  <li>13 hrs</li>
                  <li>18 min</li>
                </ul>
              </div>
              <div class="caption">
                <h4><a href="single-package-right-sidebar.html" class="captionTitle">Quisque Placerat Nunc</a></h4>
                <p>Vivamus eu mattis nibh. Quisque eget ipsum at odio fringilla consequat vel id erat. Suspendisse non feugiat mi.</p>
                <div class="detailsInfo">
                  <h5>
                    <span>Start From</span>
                    $399
                  </h5>
                  <ul class="list-inline detailsBtn">
                    <li><a href="single-package-right-sidebar.html" class="btn buttonTransparent buttonCustomPrimary">Details</a></li>
                    <li><a href='booking-1.html' class="btn buttonTransparent buttonCustomPrimary">Book now</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <div class="btnArea">
              <a href="packages-grid.html" class="btn buttonTransparent">view all</a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- PROMOTION PARALLAX -->
    <!-- DESTINATIONS -->
    <!-- COUNTING PARALLAX -->
    <section class="countUpSection">
      <div class="container">
        <div class="row">
          <div class="col-sm-3 col-xs-6">
            <div class="text-center">
              <div class="icon">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
              </div>
              <div class="counter">179</div>
              <h5>Destinations</h5>
            </div>
          </div>
          <div class="col-sm-3 col-xs-6">
            <div class="text-center">
              <div class="icon">
                <i class="fa fa-gift" aria-hidden="true"></i>
              </div>
              <div class="counter">48</div>
              <h5>tour pack</h5>
            </div>
          </div>
          <div class="col-sm-3 col-xs-6">
            <div class="text-center">
              <div class="icon">
                <i class="fa fa-smile-o" aria-hidden="true"></i>
              </div>
              <div class="counter">4562</div>
              <h5>happy clients</h5>
            </div>
          </div>
          <div class="col-sm-3 col-xs-6">
            <div class="text-center">
              <div class="icon">
                <i class="fa fa-life-ring" aria-hidden="true"></i>
              </div>
              <div class="counter">24</div>
              <h5>hours support</h5>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- TOUR PACKAGES -->
    <section class="whiteSection">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="sectionTitle">
              <h2><span>Our Packages</span></h2>
              <p>Ut facilisis facilisis metus quis semper</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <div class="filter-container isotopeFilters">
              <ul class="list-inline filter">
                <li class="active"><a href="#" data-filter="*">All Places</a></li>
                <li><a href="#" data-filter=".asia">Asia</a></li>
                <li><a href="#" data-filter=".america">America</a></li>
                <li><a href="#" data-filter=".africa">Africa</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row isotopeContainer">
            <div class="col-sm-4 isotopeSelector asia">
              <article class="">
                <figure>
                  <img src="img/home/packages/packages-1.jpg" alt="">
                  <h4>Vestibulum Tour</h4>
                  <div class="overlay-background">
                    <div class="inner"></div>
                  </div>
                  <div class="overlay">
                    <a class="fancybox-pop" href="single-package-fullwidth.html">
                    <div class="overlayInfo">
                      <h5>from <span>$399</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>27 Jan, 2017</p>
                    </div>
                    </a>
                  </div>
                </figure>
              </article>
            </div>
            <div class="col-sm-4 isotopeSelector america africa">
              <article class="">
                <figure>
                  <img src="img/home/packages/packages-2.jpg" alt="">
                  <h4>Maecenas Tour</h4>
                  <div class="overlay-background">
                    <div class="inner"></div>
                  </div>
                  <div class="overlay">
                  <a class="fancybox-pop" href="single-package-fullwidth.html">
                      <div class="overlayInfo">
                        <h5>from <span>$599</span></h5>
                        <p><i class="fa fa-calendar" aria-hidden="true"></i>09 Feb, 2017</p>
                      </div>
                    </a>
                  </div>
                </figure>
              </article>
            </div>
            <div class="col-sm-4 isotopeSelector africa">
              <article class="">
                <figure>
                  <img src="img/home/packages/packages-3.jpg" alt="">
                  <h4>Lobortis Tour</h4>
                  <div class="overlay-background">
                    <div class="inner"></div>
                  </div>
                  <div class="overlay">
                    <a class="fancybox-pop" href="single-package-fullwidth.html">
                    <div class="overlayInfo">
                      <h5>from <span>$299</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>14 Feb, 2017</p>
                    </div>
                    </a>
                  </div>
                </figure>
              </article>
            </div>
            <div class="col-sm-4 isotopeSelector asia america">
              <article class="">
                <figure>
                  <img src="img/home/packages/packages-4.jpg" alt="">
                  <h4>Leo Lacus Tour</h4>
                  <div class="overlay-background">
                    <div class="inner"></div>
                  </div>
                  <div class="overlay">
                    <a class="fancybox-pop" href="single-package-fullwidth.html">
                    <div class="overlayInfo">
                      <h5>from <span>$399</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>11 Jan, 2017</p>
                    </div>
                    </a>
                  </div>
                </figure>
              </article>
            </div>
            <div class="col-sm-4 isotopeSelector america">
              <article class="">
                <figure>
                  <img src="img/home/packages/packages-5.jpg" alt="">
                  <h4>Nullam Tour</h4>
                  <div class="overlay-background">
                    <div class="inner"></div>
                  </div>
                  <div class="overlay">
                    <a class="fancybox-pop" href="single-package-fullwidth.html">
                    <div class="overlayInfo">
                      <h5>from <span>$199</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>02 Feb, 2017</p>
                    </div>
                    </a>
                  </div>
                </figure>
              </article>
            </div>
            <div class="col-sm-4 isotopeSelector africa asia">
              <article class="">
                <figure>
                  <img src="img/home/packages/packages-6.jpg" alt="">
                  <h4>Hendrerit Tour</h4>
                  <div class="overlay-background">
                    <div class="inner"></div>
                  </div>
                  <div class="overlay">
                    <a class="fancybox-pop" href="single-package-fullwidth.html">
                    <div class="overlayInfo">
                      <h5>from <span>$799</span></h5>
                      <p><i class="fa fa-calendar" aria-hidden="true"></i>26 Feb, 2017</p>
                    </div>
                    </a>
                  </div>
                </figure>
              </article>
            </div>
        </div>
      </div>
    </section>


    <!-- INQUIRY MODAL -->
    <div class="modal fade bookingModal modalBook" id="inquiryModal" tabindex="-1">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Inquiry About Tour</h4>
          </div>
          <div class="modal-body">
            <form action="#">
              <div class="form-group">
                <input type="text" class="form-control" id="yourName" placeholder="Your Name">
              </div>
              <div class="form-group">
                <input type="email" class="form-control" id="yourEmail" placeholder="Your Email">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" id="phoneNumber" placeholder="Phone Number">
              </div>
              <div class="form-group">
                <textarea class="form-control" rows="3" placeholder="Message"></textarea>
              </div>
              <button type="submit" class="btn buttonCustomPrimary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
<!-- FOOTER -->
<footer>
<div class="container">
  <div class="row">
    <h2>Testimonials</h2>
  </div>
  <div class='row'>
    <div class='col-md-12'>
      <div class="carousel slide media-carousel" id="media">
        <div class="carousel-inner">
          <div class="item  active">
            <div class="row">
              <div class="col-md-4">
				<div class="row">	
					<div class="col-md-4">
						<img alt="" src="img/about-us/team-01.jpg">
					</div>
					<div class="col-md-8">
						I would like to thank Akanksha and the team for the fantastic work on content writing for my site. I love what you have done.
					</div>	
				</div>
              </div>          
              <div class="col-md-4">
				<div class="row">	
					<div class="col-md-4">
						<img alt="" src="img/about-us/team-01.jpg">
					</div>
					<div class="col-md-8">
						I would like to thank Akanksha and the team for the fantastic work on content writing for my site. I love what you have done.
					</div>	
				</div>
              </div>
              <div class="col-md-4">
				<div class="row">	
					<div class="col-md-4">
						<img alt="" src="img/about-us/team-01.jpg">
					</div>
					<div class="col-md-8">
						I would like to thank Akanksha and the team for the fantastic work on content writing for my site. I love what you have done.
					</div>	
				</div>
              </div>        
            </div>
          </div>
          <div class="item">
            <div class="row">
              <div class="col-md-4">
				<div class="row">	
					<div class="col-md-4">
						<img alt="" src="img/about-us/team-01.jpg">
					</div>
					<div class="col-md-8">
						I would like to thank Akanksha and the team for the fantastic work on content writing for my site. I love what you have done.
					</div>	
				</div>
              </div>          
              <div class="col-md-4">
				<div class="row">	
					<div class="col-md-4">
						<img alt="" src="img/about-us/team-01.jpg">
					</div>
					<div class="col-md-8">
						I would like to thank Akanksha and the team for the fantastic work on content writing for my site. I love what you have done.
					</div>	
				</div>
              </div>
              <div class="col-md-4">
				<div class="row">	
					<div class="col-md-4">
						<img alt="" src="img/about-us/team-01.jpg">
					</div>
					<div class="col-md-8">
						I would like to thank Akanksha and the team for the fantastic work on content writing for my site. I love what you have done.
					</div>	
				</div>
              </div>        
            </div>
          </div>
        </div>
        <a data-slide="prev" href="#media" class="left carousel-control">‹</a>
        <a data-slide="next" href="#media" class="right carousel-control">›</a>
      </div>                          
    </div>
  </div>
</div>
  <div class="copyRight clearfix">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-push-6 col-xs-12">
          <ul class="list-inline">
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Support</a></li>
            <li><a href="#">Blog</a></li>
          </ul>
        </div>
        <div class="col-sm-6 col-sm-pull-6 col-xs-12">
          <div class="copyRightText">
            <p>Copyright © 2016. All Rights Reserved by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
</div>

<!-- Signup Modal -->
<div class="modal fade signupLoging" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content modalContentCustom">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create your account</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="">
          <div class="form-group">
            <input type="text" class="form-control bg-ash" id="exampleInputEmail1" placeholder="Full Name">
          </div>
          <div class="form-group">
            <input type="email" class="form-control bg-ash" id="exampleInputPassword1" placeholder="Email">
          </div>
          <div class="form-group">
            <input type="password" class="form-control bg-ash" id="exampleInputPassword1" placeholder="Password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> I agree to the terms of use and privacy.
            </label>
          </div>
          <button type="submit" class="btn btn-default">Login</button>
        </form>
        <div class="or">
          or
        </div>
        <a class="btn btn-default btnSocial"  href="#">Log in with facebook</a>
      </div>

      <div class="modal-footer">
          <div class="dontHaveAccount">
            <p>Don’t have an Account?<a href=""> Sign up</a></p>
          </div>
      </div>
    </div>
  </div>
</div>

<!-- Login Modal -->
<div class="modal fade signupLoging" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content modalContentCustom">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Log in to your account</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="">
          <div class="form-group">
            <input type="email" class="form-control bg-ash" id="exampleInputPassword1" placeholder="Email">
          </div>
          <div class="form-group">
            <input type="password" class="form-control bg-ash" id="exampleInputPassword1" placeholder="Password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember me
            </label>
            <a class="forgotPass clerfix" href="">Fogot Password?</a>
          </div>
          <button type="submit" class="btn btn-default">Login</button>
        </form>
        <div class="or">
          or
        </div>
        <a class="btn btn-default btnSocial"  href="#">Log in with facebook</a>
      </div>

      <div class="modal-footer">
          <div class="dontHaveAccount">
            <p>Don’t have an Account?<a href=""> Sign up</a></p>
          </div>
      </div>
    </div>
  </div>
</div>