<?php 
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath().'/public/js/validate.js')
            ->prependFile($this->basePath().'/public/js/angular.min.js')
        ; ?>

    </head>
   
    <?php
    echo $this->partial('layout/adminlayout/header');
    ?>
    
        
        
            <?php echo $this->content; ?>
            <?php
    echo $this->partial('layout/adminlayout/footer');
    ?>        
               
        <?php echo $this->inlineScript() ?>
 
</html>
