<footer>

</footer><!--/#footer-->
<link href="<?= $this->basePath() . '/public/plugins/jquery-ui/jquery-ui.css' ?>" rel="stylesheet">
<link href="<?= $this->basePath() . '/public/plugins/bootstrap/css/bootstrap.min.css' ?>" rel="stylesheet">
<link href="<?= $this->basePath() . '/public/plugins/font-awesome/css/font-awesome.min.css' ?>" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?= $this->basePath() . '/public/plugins/rs-plugin/css/settings.css' ?>" media="screen">
<link rel="stylesheet" type="text/css" href="<?= $this->basePath() . '/public/plugins/selectbox/select_option1.css' ?>">
<link rel="stylesheet" type="text/css" href="<?= $this->basePath() . '/public/plugins/datepicker/datepicker.css' ?>">
<link rel="stylesheet" type="text/css" href="<?= $this->basePath() . '/public/plugins/isotope/jquery.fancybox.css' ?>">
<link rel="stylesheet" type="text/css" href="<?= $this->basePath() . '/public/plugins/isotope/isotope.css' ?>">    
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,600,700' rel='stylesheet' type='text/css'>

  <!-- CUSTOM CSS -->
  <link href="<?= $this->basePath() . '/public/css/style.css'?>" rel="stylesheet">
  <link rel="stylesheet" href="<?= $this->basePath() . '/public/css/colors/default.css'?>" id="option_color">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="<?= $this->basePath() . '/public/plugins/jquery-ui/jquery-ui.js'?>"></script>
<script src="<?= $this->basePath() . '/public/plugins/bootstrap/js/bootstrap.min.js'?>"></script>
<script src="<?= $this->basePath() . '/public/plugins/rs-plugin/js/jquery.themepunch.tools.min.js'?>"></script>
<script src="<?= $this->basePath() . '/public/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js'?>"></script>
<script src="<?= $this->basePath() . '/public/plugins/selectbox/jquery.selectbox-0.1.3.min.js'?>"></script>
<script src="<?= $this->basePath() . '/public/plugins/datepicker/bootstrap-datepicker.js'?>"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
<script src="<?= $this->basePath() . '/public/plugins/counter-up/jquery.counterup.min.js'?>"></script>
<script src="<?= $this->basePath() . '/public/plugins/isotope/isotope.min.js'?>"></script>
<script src="<?= $this->basePath() . '/public/plugins/isotope/jquery.fancybox.pack.js'?>"></script>
<script src="<?= $this->basePath() . '/public/plugins/isotope/isotope-triger.js'?>"></script>
<script src="<?= $this->basePath() . '/public/plugins/countdown/jquery.syotimer.js'?>"></script>
<script src="<?= $this->basePath() . '/public/js/custom.js'?>"></script>

<link href="<?= $this->basePath() . '/public/options/optionswitch.css'?>" rel="stylesheet">
<script src="<?= $this->basePath() . '/public/options/optionswitcher.js'?>"></script>
</body>
</html>