<body class="body-wrapper  changeHeader ">
  <div class="main-wrapper">

    <!-- HEADER -->
    <header>
      <nav class="navbar navbar-default navbar-main navbar-fixed-top" role="navigation">
		<div class="top_header">
			<div class="container">
				<div class="row">
					<div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
						<i class="fa fa-phone-square" aria-hidden="true"></i> &nbsp;8130450522 &nbsp;&nbsp;&nbsp;
						<i class="fa fa-envelope" aria-hidden="true"></i>&nbsp; raviducat@gmail.com
					</div>
					<div class="col-sm-6 col-md-6 col-lg-6 col-xs-12 pull-right">
						<a style="color:#fff;" class="pull-right" href="" data-toggle="modal" data-target="#signup">Signup</a>
						<a style="color:#fff;margin-right:10px;" class="pull-right" href="" data-toggle="modal" data-target="#login">Login</a>
					</div>					
				</div>
			</div>
		</div>
        <div class="container">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
				<a class="navbar-brand" href="index.html"></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
<li class="dropdown singleDrop active">
<a href="index.html">Home</a>
</li>
<li class="dropdown singleDrop">
	<a href="pakagelist.html">tour packages</a>
</li>
<li class="dropdown singleDrop">
	<a href="aboutus.html">about us</a>
</li>
<li class="dropdown singleDrop">
	<a href="contactus.html">contact us</a>
</li>
<li class="dropdown singleDrop">
	<a href="gallery.html">gallery</a>
</li>             
              <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="searchIcon"><i class="fa fa-search" aria-hidden="true"></i></span></a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li>
                    <span class="input-group">
                      <input type="text" class="form-control" placeholder="Search..." aria-describedby="basic-addon2">
                      <span class="input-group-addon" id="basic-addon2">Search</span>
                    </span>
                  </li>
                </ul>
              </li>
            </ul>
          </div>

        </div>
      </nav>
    </header>
    
    <script>
        var serverUrl ='<?php echo $GLOBALS['SITE_ADMIN_URL']; ?>';
    </script>
    
    